# Generated by Django 5.2 on 2025-05-01 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "idade",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(150),
                        ]
                    ),
                ),
                ("morada", models.CharField(max_length=200)),
                ("observacoes", models.TextField(max_length=500)),
            ],
        ),
    ]
